# Generated by Django 3.2.8 on 2022-10-12 18:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2022, 10, 12, 23, 32, 39, 6885), null=True)),
                ('last_modified_date', models.DateTimeField(default=datetime.datetime(2022, 10, 12, 23, 32, 39, 6885), null=True)),
                ('name', models.CharField(max_length=75, verbose_name='product_name')),
                ('product_sku', models.CharField(max_length=50, verbose_name='product_sku')),
                ('weight', models.FloatField()),
                ('cart_description', models.CharField(max_length=250, verbose_name='cart_description')),
                ('short_description', models.CharField(max_length=500, verbose_name='short_description')),
                ('long_description', models.TextField(blank=True, help_text='Not Required', verbose_name='description')),
                ('stock', models.FloatField()),
                ('slug', models.SlugField(max_length=255)),
                ('regular_price', models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': 'The price must be between 0 and 999.99.'}}, help_text='Maximum 999.99', max_digits=5, verbose_name='Regular price')),
                ('discount_price', models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': 'The price must be between 0 and 999.99.'}}, help_text='Maximum 999.99', max_digits=5, verbose_name='Discount price')),
                ('is_active', models.BooleanField(default=True, help_text='Change product visibility', verbose_name='Product visibility')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
